require:
  - rubocop-rspec

Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/console/**/*.rb'
